### ISSUE TITLE
Rails s error with Sofort Gem

### ISSUE THREAD

**Issue by matutor** [skopu/sofort#9]
When starting App with Sofort Gem installed, the following error appears:
`rails s
=> Booting Puma
=> Rails 5.1.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
/Users/Alex/github/matutor/config/initializers/sofort.rb:9:in `block in <top (required)>': undefined method `language_code=' for Sofort:Module (NoMethodError)
	from /Users/Alex/.bundle/ruby/2.4.0/gems/sofort-0.1.4/lib/sofort.rb:35:in `setup'
	from /Users/Alex/github/matutor/config/initializers/sofort.rb:1:in `<top (required)>'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `load'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `block in load'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `load'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:655:in `block in load_config_initializer'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications.rb:168:in `instrument'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:654:in `load_config_initializer'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:611:in `each'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:611:in `block in <class:Engine>'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `run'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `each'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `tsort_each_child'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/tsort.rb:415:in `call'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:58:in `run_initializers'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/application.rb:353:in `initialize!'
	from /Users/Alex/github/matutor/config/environment.rb:5:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:24:in `app'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:42:in `start'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:131:in `block in perform'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:126:in `tap'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:126:in `perform'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/command/base.rb:63:in `perform'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/command.rb:44:in `invoke'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
	from /Users/Alex/github/matutor/bin/rails:9:in `require'
	from /Users/Alex/github/matutor/bin/rails:9:in `<top (required)>'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	from /Users/Alex/.bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/Alex/github/matutor/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
`

**Comment by wtom** [comment]
Add those two gems as well.
gem 'httparty'
gem 'xml-simple'

**Comment by christianmarzian** [comment]
I have the same error. httparty and xml-simple Gems are successfully installed.

> Add those two gems as well.
> gem 'httparty'
> gem 'xml-simple'
